// Code generated by mockery v1.0.0. DO NOT EDIT.

package go2p

import mock "github.com/stretchr/testify/mock"

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

// Address provides a mock function with given fields:
func (_m *MockAdapter) Address() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Close provides a mock function with given fields:
func (_m *MockAdapter) Close() {
	_m.Called()
}

// ReadMessage provides a mock function with given fields:
func (_m *MockAdapter) ReadMessage() (*Message, error) {
	ret := _m.Called()

	var r0 *Message
	if rf, ok := ret.Get(0).(func() *Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Message)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteMessage provides a mock function with given fields: m
func (_m *MockAdapter) WriteMessage(m *Message) error {
	ret := _m.Called(m)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Message) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
